version: "3.6"

services:
  sms:
    container_name: sms-service
    image: ranckosolutionsinc/sms-service:v1.0
    # build: ./
    restart: always
    ports:
      - 7879:7879
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    networks:
      - sms-service-network
    depends_on:
      - mongo

  mongo:
    container_name: sms-service-db
    image: mongo:4.2
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - sms-service-db-data:/data/db
    networks:
      - sms-service-network

volumes:
  sms-service-db-data:

networks:
  sms-service-network:
    name: sms-service
    driver: bridge
