version: "3.6"

services:
  sms:
    container_name: hotel-elmiriam-sms-svc
    image: ranckosolutionsinc/hotel-elmiriam-sms-service:v1.0
    # build: ./
    restart: always
    ports:
      - 7879:7879
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    networks:
      - sms-service-network
    depends_on:
      - mongo

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
