version: "3.6"

services:
  hotel:
    container_name: hotel-elmiriam-bar-svc
    image: ranckosolutionsinc/hotel-elmiriam-bar-service:v1.0-alpha
    # build: ./
    restart: always
    environment:
      - PORT=8004
    env_file:
      - ./.env
    ports:
      - "8004:8004"
    networks:
      - hotel-elmiriam-network
    # depends_on:
    #   - mongo

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true
