services:
  auth:
    container_name: hotel-elmiriam-auth-svc
    image: ranckosolutionsinc/hotel-elmiriam-auth-service:1.0.0
    build: ./
    restart: always
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    env_file:
      - ./src/.env
    networks:
      - hotel-elmiriam-network 

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true

