version: "3.6"

services:
  auth:
    container_name: hotel-elmiriam-auth-svc
    image: ranckosolutionsinc/auth-service:0.2.0
    build: ./
    restart: always
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    env_file:
      - ./src/.env
    networks:
      - hotel-elmiriam-network
    depends_on:
      - mongo

  mongo:
    container_name: hotel-elmiriam-mongo-db
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - hotel-elmiriam-mongodb-data:/data/db
    networks:
      - hotel-elmiriam-network

volumes:
  hotel-elmiriam-mongodb-data:

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
