services:
  auth:
    container_name: hotel-elmiriam-auth-svc
    image: ranckosolutionsinc/hotel-elmiriam-auth-service:1.0.0
    build: ./
    restart: always
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    env_file:
      - ./src/.env
    networks:
      - hotel-elmiriam-network 
    depends_on:
      - mongo

  mongo:
    container_name: hotel-elmiriam-mongo-db
    image: mongo:4.2
    restart: always
    ports:
     - 27017:27017
    # environment:
    #  - MONGO_INITDB_DATABASE=${MONGO_INITDB_ROOT_DATABASE}     
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - hotel-elmiriam-mongodb-data:/data/db
    #  - ./mongo-entrypoint/:/docker-entrypoint-initdb.d/"  
    networks:
      - hotel-elmiriam-network

  mongo-express:
    container_name: hotel-elmiriam-mongo-compass       
    image: mongo-express:latest
    ports: 
      - 8081:8081    
    # environement:
    #   - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    #   - ME_CONFIG_MONGODB_URL=http://mongo:27017?ssl=false
    #   - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
    #   - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    networks:
      - hotel-elmiriam-network     

volumes:
  hotel-elmiriam-mongodb-data:

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true

