services:
  checkout:
    container_name: hotel-elmiriam-checkout-svc
    image: ranckosolutionsinc/hotel-elmiriam-checkout-service:v1.0
    # build: ./
    restart: always
    environment:
      - PORT=8008
      - RABBITMQ_URL=${RABBITMQ_URL}
      - INTASEND_API_TOKEN=${INTASEND_API_TOKEN}
      - INTASEND_PUBLISHABLE_KEY=${INTASEND_PUBLISHABLE_KEY}
      - INTASEND_TEST_MODE=${INTASEND_TEST_MODE}
    # env_file:
    #   - ./.env
    ports:
      - "8008:8008"
    networks:
      - hotel-elmiriam-network

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true  
