version: "3.6"

services:
  mail:
    container_name: hotel-elmiriam-mail-svc
    image: ranckosolutionsinc/hotel-elmiriam-mail-service:v1.0
    # build: ./
    restart: always
    ports:
      - 3300:3300
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    networks:
      - mail-service-network

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam    
    driver: bridge
