version: "3.6"

services:
  mail:
    container_name: mail-service
    image: ranckosolutionsinc/mail-service:v1.0
    # build: ./
    restart: always
    ports:
      - 3300:3300
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    networks:
      - mail-service-network

networks:
  mail-service-network:
    name: mail-service
    driver: bridge
