version: '3.6'

services:
  gateway:
    image: kong:3.0.2
    container_name: kong-gateway
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8009:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
    networks:
      - hotel-elmiriam-network

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
