version: "3.6"

services:
  hotel:
    container_name: hotel-elmiriam-hotel-svc
    image: ranckosolutionsinc/hotel-service:1.0-alpha
    # build: ./
    restart: always
    environment:
      - PORT=8003
    env_file:
      - ./src/.env
    ports:
      - "8003:8003"
    networks:
      - hotel-elmiriam-network
    # depends_on:
    #   - mongo

networks:
  hotel-elmiriam-network:
    name: hotel-elmiriam
    driver: bridge
    external: true  
